// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxes0sPSps_hQo5BUrFLD-2i9cdMR7krw',
    appId: '1:574084460310:web:ac1735e3e0b94959782a37',
    messagingSenderId: '574084460310',
    projectId: 'music-player-app-85a31',
    authDomain: 'music-player-app-85a31.firebaseapp.com',
    storageBucket: 'music-player-app-85a31.firebasestorage.app',
    measurementId: 'G-TZCQBVNZGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVCqisGEWqgVmifOVSJNfSW9TjlBfx0pc',
    appId: '1:574084460310:android:f580513d382d96c5782a37',
    messagingSenderId: '574084460310',
    projectId: 'music-player-app-85a31',
    storageBucket: 'music-player-app-85a31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwh2fscqLhGYun4YXW7r0WmET-DJWFpls',
    appId: '1:574084460310:ios:d8b8d60b5380f09e782a37',
    messagingSenderId: '574084460310',
    projectId: 'music-player-app-85a31',
    storageBucket: 'music-player-app-85a31.firebasestorage.app',
    iosBundleId: 'com.example.musicPlayerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwh2fscqLhGYun4YXW7r0WmET-DJWFpls',
    appId: '1:574084460310:ios:d8b8d60b5380f09e782a37',
    messagingSenderId: '574084460310',
    projectId: 'music-player-app-85a31',
    storageBucket: 'music-player-app-85a31.firebasestorage.app',
    iosBundleId: 'com.example.musicPlayerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxes0sPSps_hQo5BUrFLD-2i9cdMR7krw',
    appId: '1:574084460310:web:dd004d52c9f70156782a37',
    messagingSenderId: '574084460310',
    projectId: 'music-player-app-85a31',
    authDomain: 'music-player-app-85a31.firebaseapp.com',
    storageBucket: 'music-player-app-85a31.firebasestorage.app',
    measurementId: 'G-JS9RRHRD8E',
  );
}
